### PR TITLE
Update tests from CouchDB master

### PR DESCRIPTION
**Pull request by marten-de-vries**
Based on #6.

This updates all tests against latest couchdb master; instead of commenting out tests this uses a ``skip(reason, function_containing_the_skipped_code)`` function which prints to stdout so it's clear *which* things are skipped. Also adds nice colors in the terminal for overview & makes this run out of the box on my linux laptop.

I recommend not using the github merge button for this but fast-forward merging (just 'git merge') instead: it'll make updating from couchdb master in the future slightly easier to understand.

pouchdb/express-pouchdb#169 contains the express-pouchdb changes made while writing this.

I hope we can move couchdb-harness under the pouchdb org as advised by @nolanlawson in #6. A new release would also be nice after this is merged so Travis can pick this up as part of the express-pouchdb/pouchdb-server test suite.

### CODE REVIEW

**Comment by nolanlawson** [comment]
:+1: 

@nick-thompson could you please move this to the pouchdb org, and also add the following npm users as maintainers?

```
npm owner add nolanlawson
npm owner add commandoline
```

**Comment by marten-de-vries** [comment]
If this is going to be a pouchdb repo I can as well start using that commit message style now. :)

**Comment by nick-thompson** [comment]
@nolanlawson @marten-de-vries sorry it took me so long to get to this. I'm happy to have it under the pouchdb org and it's great to see y'all working on it. I've added both of you to the npm owners list as well.

Let me know if there's anything else you need!

**Comment by marten-de-vries** [comment]
@nick-thompson Thanks!

**Comment by marten-de-vries** [comment]
Just released a new version based on this merge. For now I played it safe and chose 0.1.0, but I think we can go to 1.0.0 next time since the API is stable - even this PR, which completely replaced the tests, didn't change the API.

**Comment by nolanlawson** [comment]
Thanks @nick-thompson!

**Pull request merged**
