### PR TITLE
(#8) - Enable attachment tests

### PR DESCRIPTION
**Pull request by marten-de-vries**
Based on #7.

### CODE REVIEW

**Comment by nolanlawson** [comment]
So I take it that, for all these PRs, you have a corresponding fix in express-pouchdb? If that's the case, then let's just merge all these PRs here and then see if they pass the Travis tests in express-pouchdb.

**Comment by marten-de-vries** [comment]
@nolanlawson If you want to see cochdb-harness pass them all separately, the only way to do it is to: 
- first merge the couchdb-harness PR,
- then run Travis for the related express-pouchdb PR,
- and merge that when it's green.
- Repeat.

I'm going to start that process with this PR first.

If I'd merge all the couchdb-harness PRs at once, all the express-pouchdb PRs would fail on test modifications not related to them. A BAIL=0 env option could mitigate the problem to the file level so we could at least manually see the difference, but that's currently not implemented.

**Comment by marten-de-vries** [comment]
Hmm, that also requires a new npm release after each commit. Not really handy but probably still cleaner than making pouchdb-server just use latest git. (releasing 0.1.1)

**Comment by nolanlawson** [comment]
Ahhh, I see the issue. OK, I guess one-at-a-time is fine, but feel free to timebomb if I'm not quick on the draw. :)

**Comment by nolanlawson** [comment]
On second thought, why don't we do this:

* Merge all these couchdb-harness fixes at once
* Do a mega-PR in express-pouchdb with all your changes
* Check that the mega PR passes in Travis, then merge individually

?

**Comment by marten-de-vries** [comment]
Hmm, that's easier. Will do.

**Pull request merged**
